language: node_js
node_js:
  - 0.12
sudo: false
addons:
  apt:
    packages:
    - libpng-dev
    - libatlas-base-dev
    - libblas-dev
    - libcairo2-dev
    - libjpeg8-dev
    - libpango1.0-dev
    - libgif-dev
    - build-essential
    - g++
before_install:
  - wget https://s3-us-west-2.amazonaws.com/cdn.thegrid.io/caliper/libvips/libccv-0.1.1.tar.gz
  - mkdir $HOME/libccv
  - echo $HOME/libccv
  - tar -xvzf libccv-0.1.1.tar.gz -C $HOME/libccv
before_script:
- npm install -g grunt-cli
deploy:
  provider: npm
  email: vilson@void.cc
  api_key:
    secure: P/wpLx5s5daDjskxi3CWHNnalAqgozJrreM/yNWtku0uQykluyIJx4ed5ji05JqXYdhTul4QxYR/c93cFJmuKW8GTC1w3qs27R1WSC6OpnW/z3AXdJ8Flu3nMTfxUzpuHO3dGabQ0rsHQ8VbJYvO7WT3Zw8cM289pJgxBSGcyz0=
  on:
    tags: true
    repo: noflo/noflo-ccv
